name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "hunter-smp-template-1.21.11 (1)"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
      - run: chmod +x gradlew && ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: mod
          path: "hunter-smp-template-1.21.11 (1)/build/libs/*.jar"
